elifeLibrary({
    def commit
    stage 'Checkout', {
        checkout scm
        commit = elifeGitRevision()
    }

    stage 'Project tests', {
        # test config (see libraries formula)
        # - https://github.com/elifesciences/elife-libraries-formula/blob/1f275e206f2b398ce49ba14e4a277905a5b8d332/salt/elife-libraries/init.sls#L132-L138
        sh "rm -f app.cfg"
        sh "cp /etc/ubr-test-app.cfg app.cfg"
        withCommitStatus({
            sh "mise exec python@3.8 -- ./project_tests.sh"
        }, 'project_tests@3.8', commit)
        withCommitStatus({
            sh "mise exec python@3.10 -- ./project_tests.sh"
        }, 'project_tests@3.10', commit)
        echo 'Checking changes have not been generated by the style checker. If this fails, run .lint.sh from within your venv.'
        sh 'git diff --exit-code'
    }

    elifeMainlineOnly {
        stage 'Publishing to master', {
            elifeGitMoveToBranch commit, 'master'
        }
    }
})
