elifeLibrary({
    def commit
    stage 'Checkout', {
        checkout scm
        commit = elifeGitRevision()
    }

    stage 'Project tests', {
        elifeLocalTests "./project_tests.sh"
        echo 'Checking changes have not been generated by the style checker. If this fails, run .lint.sh from within your venv.'
        sh 'git diff --exit-code'
    }

    elifeMainlineOnly {
        stage 'Publishing to master', {
            elifeGitMoveToBranch commit, 'master'
        }
    }
})
