elifeLibrary({
    def commit
    stage 'Checkout', {
        checkout scm
        commit = elifeGitRevision()
    }

    stage 'Project tests', {
        parallel([
            'Project tests (python@3.8)': {
                withCommitStatus({
                    sh "mise exec python@3.8 -- ./project_tests.sh"
                }, 'project_tests@3.8', commit)
            },
            'Project tests (python@3.10)': {
                withCommitStatus({
                    sh "mise exec python@3.10 -- ./project_tests.sh"
                }, 'project_tests@3.10', commit)
            }
        ])
        echo 'Checking changes have not been generated by the style checker. If this fails, run .lint.sh from within your venv.'
        sh 'git diff --exit-code'
    }

    elifeMainlineOnly {
        stage 'Publishing to master', {
            elifeGitMoveToBranch commit, 'master'
        }
    }
})
