name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: docker compose -f docker-compose.ci.yaml run --build --rm lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This seems to work faster than pulling during docker compose up
      - name: Pull images
        run: docker compose -f docker-compose.ci.yaml pull --quiet
      - name: Run test suite in container
        run: docker compose -f docker-compose.ci.yaml run --build --rm test
      - name: debug logs
        if: failure()
        run: docker compose logs
